import { Link } from 'react-router-dom'
import ProductSelector from '../components/ProductSelector'
import SEO from '../components/SEO'
import { getWhyPillars } from '../data/company'
export default function Home({lang='en'}) {
 const ar=lang==='ar'; const t=(en,arText)=>ar?arText:en
 return <main>
  <SEO title={t('DAOUDCO | Agricultural polyethylene films · Jordan','داودكو | أفلام البولي إيثيلين الزراعية · الأردن')} description={t('Agricultural polyethylene film manufacturing in Jordan since 1977. Five-layer co-extrusion and films up to 16 metres wide.','تصنيع أفلام البولي إيثيلين الزراعية في الأردن منذ عام 1977. بثق مشترك بخمس طبقات وأفلام بعروض تصل إلى 16 متراً.')}/>
  <section className="hero"><img src="/images/daoudco/greenhouse-aerial.jpg" alt={t('Agricultural greenhouses viewed from above','بيوت زراعية محمية من الأعلى')} fetchPriority="high"/><div className="hero-copy wrap"><span className="eyebrow">{t('DAOUDCO · ESTABLISHED 1977 · JORDAN','داودكو · تأسست عام 1977 · الأردن')}</span><h1>{t('Agricultural films.','أفلام زراعية.')}<br/>{t('Manufactured with experience.','نصنعها بخبرة.')}</h1><p>{t('Polyethylene film manufacturing for protected cultivation, productive land and the people who grow.','نصنّع أفلام البولي إيثيلين للزراعة المحمية والأرض المنتجة ومن يعملون على زراعتها.')}</p><div className="actions"><Link className="btn" to="/products">{t('Explore our products','استكشف منتجاتنا')} <span aria-hidden="true">{ar?'←':'→'}</span></Link><Link className="btn ghost" to="/contact">{t('Request a quote','اطلب عرض سعر')}</Link></div></div></section>
  <section className="cred wrap" aria-label={t('Company facts','حقائق عن الشركة')}><div><strong>1977</strong><span>{t('Established in Jordan','تأسست في الأردن')}</span></div><div><strong>{t('5-layer','5 طبقات')}</strong><span>{t('Co-extrusion technology','تقنية البثق المشترك')}</span></div><div><strong>{t('Up to 16 m','حتى 16 متراً')}</strong><span>{t('Film width','عرض الفيلم')}</span></div><div><strong>{t('Jordan','الأردن')}</strong><span>{t('Our manufacturing home','موطن صناعتنا')}</span></div></section>
  <section className="split wrap company-intro"><img src="/images/daoudco/production-facility.jpg" alt={t('DAOUDCO manufacturing facility in Jordan','منشأة داودكو الصناعية في الأردن')} loading="lazy"/><div><span className="eyebrow">{t('OUR COMPANY','شركتنا')}</span><h2>{t('Rooted in Jordan. Focused on agriculture.','جذورنا في الأردن. واهتمامنا بالزراعة.')}</h2><p>{t('Since 1977, DAOUDCO has specialized in agricultural polyethylene films. We bring manufacturing experience and an understanding of agricultural needs to films for crop protection, soil covering and protected cultivation.','منذ عام 1977، تتخصص داودكو في أفلام البولي إيثيلين الزراعية. نجمع الخبرة الصناعية وفهم الاحتياجات الزراعية لإنتاج أفلام لحماية المحاصيل وتغطية التربة والزراعة المحمية.')}</p><Link className="text-link" to="/about">{t('Discover our story →','تعرّف على قصتنا ←')}</Link></div></section>
  <section className="catalogue-section"><div className="wrap section-head"><span className="eyebrow">{t('THE PRODUCT RANGE','مجموعة المنتجات')}</span><h2>{t('The right film for your application.','الفيلم المناسب لتطبيقك الزراعي.')}</h2><p>{t('Explore agricultural films by application, characteristics and technical specifications.','استكشف الأفلام الزراعية حسب التطبيقات والخصائص والمواصفات الفنية.')}</p><ProductSelector lang={lang}/></div></section>
  <section className="wrap why-section"><span className="eyebrow">{t('WHY DAOUDCO','لماذا داودكو')}</span><h2>{t('Experience behind every layer.','خبرة وراء كل طبقة.')}</h2><div className="cards three pillars">{getWhyPillars(lang).map(([h,b],i)=><article key={h}><span className="card-index">0{i+1}</span><h3>{h}</h3><p>{b}</p></article>)}</div></section>
  <section className="manufacturing-band"><div className="wrap split"><div><span className="eyebrow">{t('MANUFACTURING CAPABILITY','قدرات التصنيع')}</span><h2>{t('Five layers. One considered process.','خمس طبقات. وعملية إنتاج متكاملة.')}</h2><p>{t('Five-layer co-extrusion, automated raw material handling and quality-control stages support the production of agricultural films up to 16 metres wide.','يدعم البثق المشترك بخمس طبقات والمناولة الآلية للمواد الخام ومراحل ضبط الجودة إنتاج أفلام زراعية بعروض تصل إلى 16 متراً.')}</p><Link className="btn light" to="/manufacturing">{t('Inside our manufacturing','تعرّف على التصنيع لدينا')}</Link></div><img src="/images/daoudco/coextrusion-line.jpg" alt={t('DAOUDCO co-extrusion production tower','برج إنتاج البثق المشترك في داودكو')} loading="lazy"/></div></section>
  <section className="cta wrap"><div><span className="eyebrow">{t('LET’S TALK AGRICULTURE','لنتحدث عن احتياجاتك الزراعية')}</span><h2>{t('Tell us what you need to cover.','أخبرنا باحتياجاتك من الأغطية.')}</h2><p>{t('Our team can help you discuss film selection and your order requirements.','يساعدك فريقنا في مناقشة اختيار الفيلم ومتطلبات طلبك.')}</p></div><Link className="btn" to="/contact">{t('Contact our team','تواصل مع فريقنا')}</Link></section>
 </main>
}
