import { Link, Navigate, useParams } from 'react-router-dom'
import SEO from '../components/SEO'
import ProductImage from '../components/ProductImage'
import { getProduct, products } from '../data/products'
import { localizeProduct } from '../data/productArabic'
import { ui } from '../content'
import { whatsappUrl } from '../utils/contact'
export default function ProductDetail({lang='en'}) {
 const {slug}=useParams(); const p=localizeProduct(getProduct(slug),lang); const ar=lang==='ar'; const t=ui[lang]
 if(!p) return <Navigate to="/products" replace/>
 const related=products.filter(x=>x.slug!==p.slug).slice(0,3).map(x=>localizeProduct(x,lang))
 const actions=<div className="actions"><Link className="btn" to={`/contact?product=${p.slug}`}>{t.quote}</Link><a className="btn ghost" href={whatsappUrl(ar?`مرحباً داودكو، أود الحصول على معلومات عن ${p.name}.`:`Hello Daoudco, I would like more information about ${p.name}.`)} target="_blank" rel="noopener noreferrer">{t.ask}</a></div>
 return <main><SEO title={`${p.name} | ${ar?'داودكو':'DAOUDCO'}`} description={p.seo}/><section className="product-hero"><ProductImage product={p} lang={lang}/><div className="wrap"><div><nav className="breadcrumbs" aria-label={ar?'مسار التنقل':'Breadcrumb'}><Link to="/">{ar?'الرئيسية':'Home'}</Link> / <Link to="/products">{ar?'المنتجات':'Products'}</Link> / <span aria-current="page">{p.name}</span></nav><h1>{p.name}</h1><p>{p.description}</p>{actions}</div></div></section>
 <section className="wrap product-detail"><div><h2>{ar?'الخصائص الرئيسية':'Key characteristics'}</h2><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><h2>{ar?'التطبيقات الرئيسية':'Main applications'}</h2><div className="chips">{p.applications.map(a=><span key={a}>{a}</span>)}</div><h2>{ar?'خيارات المنتج':'Product variations'}</h2>{p.variations.map(v=><article className="detail-box" key={v.name}><h3>{v.name}</h3><ul>{v.details.map(d=><li key={d}>{d}</li>)}</ul></article>)}{p.additives.length>0&&<><h2>{ar?'الإضافات المتاحة':'Available additives'}</h2><div className="chips">{p.additives.map(a=><span key={a}>{a}</span>)}</div></>}</div>
 <aside><h2>{ar?'المواصفات الفنية':'Technical specifications'}</h2><table><caption>{ar?`مقاسات ${p.name}`:`${p.name} dimensions`}</caption><tbody>{p.specifications.map(([k,v])=><tr key={k}><th scope="row">{k}</th><td>{v}</td></tr>)}</tbody></table><p className="muted">{ar?'تواصل معنا لتأكيد المقاسات وخيارات الإضافات وعمر الخدمة المناسب لظروف الاستخدام.':'Contact us to confirm dimensions, additive options, and service life for your operating conditions.'}</p><h2>{ar?'المستندات الفنية':'Technical documents'}</h2>{p.technicalDocuments.length?p.technicalDocuments.map(d=><a key={d.file} className="doc-card" href={d.file} target="_blank" rel="noopener noreferrer">{d.title}<small>{d.note}</small></a>):<p className="muted">{ar?'للحصول على المواصفات الفنية التفصيلية، يرجى التواصل مع فريقنا.':'Please contact our team for detailed technical information.'}</p>}</aside></section>
 <section className="wrap"><h2>{ar?'منتجات ذات صلة':'Related products'}</h2><div className="cards three">{related.map(r=><Link className="product-card" to={`/products/${r.slug}`} key={r.slug}><ProductImage product={r} lang={lang}/><h3>{r.name}</h3><p>{r.shortDescription}</p></Link>)}</div></section><section className="wrap cta-band"><h2>{ar?'ناقش متطلبات مشروعك معنا':'Discuss your project requirements'}</h2><p>{ar?'أخبرنا عن المحصول والتطبيق والمقاسات المطلوبة لمساعدتك في اختيار المنتج.':'Tell us about your crop, application, and required dimensions so we can help you select a film.'}</p>{actions}</section></main>
}
